/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */
export type LessonCompletion = {
    _id: string;
    _type: "lessonCompletion";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    student?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "student";
    };
    lesson?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "lesson";
    };
    module?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "module";
    };
    course?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "course";
    };
    completedAt?: string;
};
export type Module = {
    _id: string;
    _type: "module";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    lessons?: Array<{
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: "lesson";
    }>;
};
export type Lesson = {
    _id: string;
    _type: "lesson";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    slug?: Slug;
    description?: string;
    videoUrl?: string;
    loomUrl?: string;
    content?: Array<{
        children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
        }>;
        style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
    }>;
};
export type Slug = {
    _type: "slug";
    current?: string;
    source?: string;
};
export type Enrollment = {
    _id: string;
    _type: "enrollment";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    student?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "student";
    };
    course?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "course";
    };
    amount?: number;
    paymentId?: string;
    enrolledAt?: string;
};
export type Student = {
    _id: string;
    _type: "student";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    firstName?: string;
    lastName?: string;
    email?: string;
    clerkId?: string;
    imageUrl?: string;
};
export type Course = {
    _id: string;
    _type: "course";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    price?: number;
    slug?: Slug;
    description?: string;
    image?: {
        asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
    };
    category?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "category";
    };
    modules?: Array<{
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: "module";
    }>;
    instructor?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "instructor";
    };
};
export type Instructor = {
    _id: string;
    _type: "instructor";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    bio?: string;
    photo?: {
        asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
    };
};
export type SanityImageCrop = {
    _type: "sanity.imageCrop";
    top?: number;
    bottom?: number;
    left?: number;
    right?: number;
};
export type SanityImageHotspot = {
    _type: "sanity.imageHotspot";
    x?: number;
    y?: number;
    height?: number;
    width?: number;
};
export type Category = {
    _id: string;
    _type: "category";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    slug?: Slug;
};
export type BlockContent = Array<{
    children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
}>;
export type SanityImagePaletteSwatch = {
    _type: "sanity.imagePaletteSwatch";
    background?: string;
    foreground?: string;
    population?: number;
    title?: string;
};
export type SanityImagePalette = {
    _type: "sanity.imagePalette";
    darkMuted?: SanityImagePaletteSwatch;
    lightVibrant?: SanityImagePaletteSwatch;
    darkVibrant?: SanityImagePaletteSwatch;
    vibrant?: SanityImagePaletteSwatch;
    dominant?: SanityImagePaletteSwatch;
    lightMuted?: SanityImagePaletteSwatch;
    muted?: SanityImagePaletteSwatch;
};
export type SanityImageDimensions = {
    _type: "sanity.imageDimensions";
    height?: number;
    width?: number;
    aspectRatio?: number;
};
export type SanityImageMetadata = {
    _type: "sanity.imageMetadata";
    location?: Geopoint;
    dimensions?: SanityImageDimensions;
    palette?: SanityImagePalette;
    lqip?: string;
    blurHash?: string;
    hasAlpha?: boolean;
    isOpaque?: boolean;
};
export type SanityFileAsset = {
    _id: string;
    _type: "sanity.fileAsset";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash?: string;
    extension?: string;
    mimeType?: string;
    size?: number;
    assetId?: string;
    uploadId?: string;
    path?: string;
    url?: string;
    source?: SanityAssetSourceData;
};
export type SanityAssetSourceData = {
    _type: "sanity.assetSourceData";
    name?: string;
    id?: string;
    url?: string;
};
export type SanityImageAsset = {
    _id: string;
    _type: "sanity.imageAsset";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash?: string;
    extension?: string;
    mimeType?: string;
    size?: number;
    assetId?: string;
    uploadId?: string;
    path?: string;
    url?: string;
    metadata?: SanityImageMetadata;
    source?: SanityAssetSourceData;
};
export type Geopoint = {
    _type: "geopoint";
    lat?: number;
    lng?: number;
    alt?: number;
};
export type AllSanitySchemaTypes = LessonCompletion | Module | Lesson | Slug | Enrollment | Student | Course | Instructor | SanityImageCrop | SanityImageHotspot | Category | BlockContent | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
export type GetCourseByIdQueryResult = {
    _id: string;
    _type: "course";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    price?: number;
    slug?: Slug;
    description?: string;
    image?: {
        asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
    };
    category: {
        _id: string;
        _type: "category";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        title?: string;
        slug?: Slug;
    } | null;
    modules: Array<{
        _id: string;
        _type: "module";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        title?: string;
        lessons: Array<{
            _id: string;
            _type: "lesson";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            title?: string;
            slug?: Slug;
            description?: string;
            videoUrl?: string;
            loomUrl?: string;
            content?: Array<{
                children?: Array<{
                    marks?: Array<string>;
                    text?: string;
                    _type: "span";
                    _key: string;
                }>;
                style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
                listItem?: "bullet" | "number";
                markDefs?: Array<{
                    href?: string;
                    _type: "link";
                    _key: string;
                }>;
                level?: number;
                _type: "block";
                _key: string;
            }>;
        }> | null;
    }> | null;
    instructor: {
        _id: string;
        _type: "instructor";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        name?: string;
        bio?: string;
        photo?: {
            asset?: {
                _ref: string;
                _type: "reference";
                _weak?: boolean;
                [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
            };
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
        };
    } | null;
} | null;
export type GetCourseBySlugQueryResult = {
    _id: string;
    _type: "course";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    price?: number;
    slug?: Slug;
    description?: string;
    image?: {
        asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
    };
    category: {
        _id: string;
        _type: "category";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        title?: string;
        slug?: Slug;
    } | null;
    modules: Array<{
        _id: string;
        _type: "module";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        title?: string;
        lessons: Array<{
            _id: string;
            _type: "lesson";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            title?: string;
            slug?: Slug;
            description?: string;
            videoUrl?: string;
            loomUrl?: string;
            content?: Array<{
                children?: Array<{
                    marks?: Array<string>;
                    text?: string;
                    _type: "span";
                    _key: string;
                }>;
                style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
                listItem?: "bullet" | "number";
                markDefs?: Array<{
                    href?: string;
                    _type: "link";
                    _key: string;
                }>;
                level?: number;
                _type: "block";
                _key: string;
            }>;
        }> | null;
    }> | null;
    instructor: {
        _id: string;
        _type: "instructor";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        name?: string;
        bio?: string;
        photo?: {
            asset?: {
                _ref: string;
                _type: "reference";
                _weak?: boolean;
                [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
            };
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
        };
    } | null;
} | null;
export type GetCoursesQueryResult = Array<{
    _id: string;
    _type: "course";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    price?: number;
    slug: string | null;
    description?: string;
    image?: {
        asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
    };
    category: {
        _id: string;
        _type: "category";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        title?: string;
        slug?: Slug;
    } | null;
    modules?: Array<{
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: "module";
    }>;
    instructor: {
        _id: string;
        _type: "instructor";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        name?: string;
        bio?: string;
        photo?: {
            asset?: {
                _ref: string;
                _type: "reference";
                _weak?: boolean;
                [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
            };
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
        };
    } | null;
}>;
export type SearchCoursesQueryResult = Array<{
    _id: string;
    _type: "course";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    price?: number;
    slug: string | null;
    description?: string;
    image?: {
        asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
    };
    category: {
        _id: string;
        _type: "category";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        title?: string;
        slug?: Slug;
    } | null;
    modules?: Array<{
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: "module";
    }>;
    instructor: {
        _id: string;
        _type: "instructor";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        name?: string;
        bio?: string;
        photo?: {
            asset?: {
                _ref: string;
                _type: "reference";
                _weak?: boolean;
                [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
            };
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
        };
    } | null;
}>;
export type ExistingCompletionQueryResult = {
    _id: string;
    _type: "lessonCompletion";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    student?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "student";
    };
    lesson?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "lesson";
    };
    module?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "module";
    };
    course?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "course";
    };
    completedAt?: string;
} | null;
export type LessonModuleCourseQueryResult = {
    _id: string;
    module: {
        _id: string;
        course: string | null;
    } | null;
} | null;
export type CourseProgressQueryResult = {
    completedLessons: Array<{
        _id: string;
        _type: "lessonCompletion";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        student?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "student";
        };
        lesson: {
            _id: string;
            _type: "lesson";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            title?: string;
            slug?: Slug;
            description?: string;
            videoUrl?: string;
            loomUrl?: string;
            content?: Array<{
                children?: Array<{
                    marks?: Array<string>;
                    text?: string;
                    _type: "span";
                    _key: string;
                }>;
                style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
                listItem?: "bullet" | "number";
                markDefs?: Array<{
                    href?: string;
                    _type: "link";
                    _key: string;
                }>;
                level?: number;
                _type: "block";
                _key: string;
            }>;
        } | null;
        module: {
            _id: string;
            _type: "module";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            title?: string;
            lessons?: Array<{
                _ref: string;
                _type: "reference";
                _weak?: boolean;
                _key: string;
                [internalGroqTypeReferenceTo]?: "lesson";
            }>;
        } | null;
        course?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "course";
        };
        completedAt?: string;
    }>;
    course: {
        _id: string;
        _type: "course";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        title?: string;
        price?: number;
        slug?: Slug;
        description?: string;
        image?: {
            asset?: {
                _ref: string;
                _type: "reference";
                _weak?: boolean;
                [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
            };
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
        };
        category?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "category";
        };
        modules: Array<{
            _id: string;
            _type: "module";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            title?: string;
            lessons: Array<{
                _id: string;
                _type: "lesson";
                _createdAt: string;
                _updatedAt: string;
                _rev: string;
                title?: string;
                slug?: Slug;
                description?: string;
                videoUrl?: string;
                loomUrl?: string;
                content?: Array<{
                    children?: Array<{
                        marks?: Array<string>;
                        text?: string;
                        _type: "span";
                        _key: string;
                    }>;
                    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
                    listItem?: "bullet" | "number";
                    markDefs?: Array<{
                        href?: string;
                        _type: "link";
                        _key: string;
                    }>;
                    level?: number;
                    _type: "block";
                    _key: string;
                }>;
            }> | null;
        }> | null;
        instructor?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "instructor";
        };
    } | null;
};
export type GetLessonByIdQueryResult = {
    _id: string;
    _type: "lesson";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    slug?: Slug;
    description?: string;
    videoUrl?: string;
    loomUrl?: string;
    content?: Array<{
        children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
        }>;
        style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
    }>;
    module: null;
} | null;
export type LessonCompletionStatusQueryResult = {
    _id: string;
    _type: "lessonCompletion";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    student?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "student";
    };
    lesson?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "lesson";
    };
    module?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "module";
    };
    course?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "course";
    };
    completedAt?: string;
} | null;
export type GetCompletionsQueryResult = {
    completedLessons: Array<{
        _id: string;
        _type: "lessonCompletion";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        student?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "student";
        };
        lesson: {
            _id: string;
            _type: "lesson";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            title?: string;
            slug?: Slug;
            description?: string;
            videoUrl?: string;
            loomUrl?: string;
            content?: Array<{
                children?: Array<{
                    marks?: Array<string>;
                    text?: string;
                    _type: "span";
                    _key: string;
                }>;
                style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
                listItem?: "bullet" | "number";
                markDefs?: Array<{
                    href?: string;
                    _type: "link";
                    _key: string;
                }>;
                level?: number;
                _type: "block";
                _key: string;
            }>;
        } | null;
        module: {
            _id: string;
            _type: "module";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            title?: string;
            lessons?: Array<{
                _ref: string;
                _type: "reference";
                _weak?: boolean;
                _key: string;
                [internalGroqTypeReferenceTo]?: "lesson";
            }>;
        } | null;
        course?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "course";
        };
        completedAt?: string;
    }>;
    course: {
        _id: string;
        _type: "course";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        title?: string;
        price?: number;
        slug?: Slug;
        description?: string;
        image?: {
            asset?: {
                _ref: string;
                _type: "reference";
                _weak?: boolean;
                [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
            };
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
        };
        category?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "category";
        };
        modules: Array<{
            _id: string;
            _type: "module";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            title?: string;
            lessons: Array<{
                _id: string;
                _type: "lesson";
                _createdAt: string;
                _updatedAt: string;
                _rev: string;
                title?: string;
                slug?: Slug;
                description?: string;
                videoUrl?: string;
                loomUrl?: string;
                content?: Array<{
                    children?: Array<{
                        marks?: Array<string>;
                        text?: string;
                        _type: "span";
                        _key: string;
                    }>;
                    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
                    listItem?: "bullet" | "number";
                    markDefs?: Array<{
                        href?: string;
                        _type: "link";
                        _key: string;
                    }>;
                    level?: number;
                    _type: "block";
                    _key: string;
                }>;
            }> | null;
        }> | null;
        instructor?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "instructor";
        };
    } | null;
};
export type UncompleteLessonStudentQueryResult = {
    _id: string;
} | null;
export type UncompleteLessonCompletionQueryResult = {
    _id: string;
} | null;
export type GetEnrolledCoursesQueryResult = {
    enrolledCourses: Array<{
        _id: string;
        _type: "enrollment";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        student?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "student";
        };
        course: {
            _id: string;
            _type: "course";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            title?: string;
            price?: number;
            slug: string | null;
            description?: string;
            image?: {
                asset?: {
                    _ref: string;
                    _type: "reference";
                    _weak?: boolean;
                    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
                };
                media?: unknown;
                hotspot?: SanityImageHotspot;
                crop?: SanityImageCrop;
                _type: "image";
            };
            category: {
                _id: string;
                _type: "category";
                _createdAt: string;
                _updatedAt: string;
                _rev: string;
                title?: string;
                slug?: Slug;
            } | null;
            modules?: Array<{
                _ref: string;
                _type: "reference";
                _weak?: boolean;
                _key: string;
                [internalGroqTypeReferenceTo]?: "module";
            }>;
            instructor: {
                _id: string;
                _type: "instructor";
                _createdAt: string;
                _updatedAt: string;
                _rev: string;
                name?: string;
                bio?: string;
                photo?: {
                    asset?: {
                        _ref: string;
                        _type: "reference";
                        _weak?: boolean;
                        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
                    };
                    media?: unknown;
                    hotspot?: SanityImageHotspot;
                    crop?: SanityImageCrop;
                    _type: "image";
                };
            } | null;
        } | null;
        amount?: number;
        paymentId?: string;
        enrolledAt?: string;
    }>;
} | null;
export type GetStudentByClerkIdQueryResult = {
    _id: string;
    _type: "student";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    firstName?: string;
    lastName?: string;
    email?: string;
    clerkId?: string;
    imageUrl?: string;
} | null;
export type IsEnrolledStudentIdQueryResult = string | null;
export type IsEnrolledEnrollmentQueryResult = {
    _id: string;
    _type: "enrollment";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    student?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "student";
    };
    course?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "course";
    };
    amount?: number;
    paymentId?: string;
    enrolledAt?: string;
} | null;
import "@sanity/client";
declare module "@sanity/client" {
    interface SanityQueries {
        "\n  *[_type == \"course\" && _id == $id][0] {\n    ...,\n    category->{...},\n    instructor->{...},\n    modules[]->{\n      ...,\n      lessons[]->{...}\n    }\n  }\n": GetCourseByIdQueryResult;
        "\n  *[_type == \"course\" && slug.current == $slug][0] {\n    ...,\n    category->{...},\n    instructor->{...},\n    modules[]->{\n      ...,\n      lessons[]->{...}\n    }\n  }\n": GetCourseBySlugQueryResult;
        "\n  *[_type == \"course\"] {\n    ...,\n    \"slug\": slug.current,\n    category->{...},\n    instructor->{...}\n  }\n": GetCoursesQueryResult;
        "\n  *[_type == \"course\" && (\n    title match $wildcard ||\n    description match $wildcard ||\n    category->title match $wildcard\n  )] {\n    ...,\n    \"slug\": slug.current,\n    category->{...},\n    instructor->{...}\n  }\n": SearchCoursesQueryResult;
        "\n  *[_type == \"lessonCompletion\"\n    && student._ref == $studentId\n    && lesson._ref == $lessonId][0]\n": ExistingCompletionQueryResult | LessonCompletionStatusQueryResult;
        "\n  *[_type == \"lesson\" && _id == $lessonId][0]{\n    _id,\n    \"module\": *[_type == \"module\" && references(^._id)][0]{\n      _id,\n      \"course\": *[_type == \"course\" && references(^._id)][0]._id\n    }\n  }\n": LessonModuleCourseQueryResult;
        "\n{\n  \"completedLessons\": *[_type == \"lessonCompletion\"\n    && student._ref == $studentId\n    && course._ref == $courseId]{\n      ...,\n      \"lesson\": lesson->{...},\n      \"module\": module->{...}\n    },\n  \"course\": *[_type == \"course\" && _id == $courseId][0]{\n    ...,\n    \"modules\": modules[]->{\n      ...,\n      \"lessons\": lessons[]->{...}\n    }\n  }\n}\n": CourseProgressQueryResult | GetCompletionsQueryResult;
        "\n  *[_type == \"lesson\" && _id == $id][0]{\n    ...,\n    \"module\": module->{\n      ...,\n      \"course\": course->{...}\n    }\n  }\n": GetLessonByIdQueryResult;
        "\n  *[_type == \"student\" && clerkId == $clerkId][0]{ _id }\n": UncompleteLessonStudentQueryResult;
        "\n  *[_type == \"lessonCompletion\"\n    && student._ref == $studentId\n    && lesson._ref == $lessonId][0]{ _id }\n": UncompleteLessonCompletionQueryResult;
        "\n    *[_type == \"student\" && clerkId == $clerkId][0]{\n      \"enrolledCourses\": *[_type == \"enrollment\" && student._ref == ^._id]{\n        ...,\n        course->{\n          ...,\n          \"slug\": slug.current,\n          \"category\": category->{ ... },\n          \"instructor\": instructor->{ ... }\n        }\n      }\n    }\n  ": GetEnrolledCoursesQueryResult;
        "*[_type == \"student\" && clerkId == $clerkId][0]": GetStudentByClerkIdQueryResult;
        "*[_type == \"student\" && clerkId == $clerkId][0]._id": IsEnrolledStudentIdQueryResult;
        "*[_type == \"enrollment\" && student._ref == $studentId && course._ref == $courseId][0]": IsEnrolledEnrollmentQueryResult;
    }
}
//# sourceMappingURL=generated.d.ts.map