/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type LessonCompletion = {
  _id: string;
  _type: "lessonCompletion";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  student?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "student";
  };
  lesson?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "lesson";
  };
  module?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "module";
  };
  course?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "course";
  };
  completedAt?: string;
};

export type Lesson = {
  _id: string;
  _type: "lesson";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  videoUrl?: string;
  loomUrl?: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  module?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "module";
  };
};

export type Module = {
  _id: string;
  _type: "module";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  lessons?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "lesson";
  }>;
  course?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "course";
  };
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Enrollment = {
  _id: string;
  _type: "enrollment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  student?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "student";
  };
  course?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "course";
  };
  amount?: number;
  paymentId?: string;
  enrolledAt?: string;
};

export type Student = {
  _id: string;
  _type: "student";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  clerkId?: string;
  imageUrl?: string;
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  price?: number;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  category?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "category";
  };
  modules?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "module";
  }>;
  instructor?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "instructor";
  };
};

export type Instructor = {
  _id: string;
  _type: "instructor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  bio?: string;
  photo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = LessonCompletion | Lesson | Module | Slug | Enrollment | Student | Course | Instructor | SanityImageCrop | SanityImageHotspot | Category | BlockContent | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ../../packages/sanity-utils/src/groq/course/getCourseById.ts
// Variable: getCourseByIdQuery
// Query: *[_type == "course" && _id == $id][0] {    _id,    _type,    _createdAt,    _updatedAt,    _rev,    title,    price,    slug,    description,    image,    category->{      _id,      _type,      _createdAt,      _updatedAt,      _rev,      title,      slug    },    instructor->{      _id,      _type,      _createdAt,      _updatedAt,      _rev,      name,      bio,      photo    },    modules[]->{      _id,      _type,      _createdAt,      _updatedAt,      _rev,      title,      course,      lessons[]->{        _id,        _type,        _createdAt,        _updatedAt,        _rev,        title,        slug,        description,        videoUrl,        loomUrl,        content,        module      }    }  }
export type GetCourseByIdQueryResult = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string | null;
  price: number | null;
  slug: Slug | null;
  description: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  category: {
    _id: string;
    _type: "category";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title: string | null;
    slug: Slug | null;
  } | null;
  instructor: {
    _id: string;
    _type: "instructor";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name: string | null;
    bio: string | null;
    photo: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  modules: Array<{
    _id: string;
    _type: "module";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title: string | null;
    course: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "course";
    } | null;
    lessons: Array<{
      _id: string;
      _type: "lesson";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title: string | null;
      slug: Slug | null;
      description: string | null;
      videoUrl: string | null;
      loomUrl: string | null;
      content: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
      module: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "module";
      } | null;
    }> | null;
  }> | null;
} | null;

// Source: ../../packages/sanity-utils/src/groq/course/getCourseBySlug.ts
// Variable: getCourseBySlugQuery
// Query: *[_type == "course" && slug.current == $slug][0] {    _id,    _type,    _createdAt,    _updatedAt,    _rev,    title,    price,    slug,    description,    image,    category->{      _id,      _type,      _createdAt,      _updatedAt,      _rev,      title,      slug    },    instructor->{      _id,      _type,      _createdAt,      _updatedAt,      _rev,      name,      bio,      photo    },    modules[]->{      _id,      _type,      _createdAt,      _updatedAt,      _rev,      title,      course,      lessons[]->{        _id,        _type,        _createdAt,        _updatedAt,        _rev,        title,        slug,        description,        videoUrl,        loomUrl,        content,        module      }    }  }
export type GetCourseBySlugQueryResult = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string | null;
  price: number | null;
  slug: Slug | null;
  description: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  category: {
    _id: string;
    _type: "category";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title: string | null;
    slug: Slug | null;
  } | null;
  instructor: {
    _id: string;
    _type: "instructor";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name: string | null;
    bio: string | null;
    photo: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  modules: Array<{
    _id: string;
    _type: "module";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title: string | null;
    course: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "course";
    } | null;
    lessons: Array<{
      _id: string;
      _type: "lesson";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title: string | null;
      slug: Slug | null;
      description: string | null;
      videoUrl: string | null;
      loomUrl: string | null;
      content: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
      module: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "module";
      } | null;
    }> | null;
  }> | null;
} | null;

// Source: ../../packages/sanity-utils/src/groq/course/getCourses.ts
// Variable: getCoursesQuery
// Query: *[_type == "course"] {    _id,    _type,    _createdAt,    _updatedAt,    _rev,    title,    price,    slug,    description,    image,    category->{      _id,      _type,      title,      slug    },    instructor->{      _id,      _type,      name,      bio,      photo    },    modules  }
export type GetCoursesQueryResult = Array<{
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string | null;
  price: number | null;
  slug: Slug | null;
  description: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  category: {
    _id: string;
    _type: "category";
    title: string | null;
    slug: Slug | null;
  } | null;
  instructor: {
    _id: string;
    _type: "instructor";
    name: string | null;
    bio: string | null;
    photo: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  modules: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "module";
  }> | null;
}>;

// Source: ../../packages/sanity-utils/src/groq/course/searchCourses.ts
// Variable: searchCoursesQuery
// Query: *[_type == "course" && (    title match $wildcard ||    description match $wildcard ||    category->title match $wildcard  )] {    _id,    _type,    _createdAt,    _updatedAt,    _rev,    title,    price,    slug,    description,    image,    category->{      _id,      _type,      title,      slug    },    instructor->{      _id,      _type,      name,      bio,      photo    },    modules  }
export type SearchCoursesQueryResult = Array<{
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string | null;
  price: number | null;
  slug: Slug | null;
  description: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  category: {
    _id: string;
    _type: "category";
    title: string | null;
    slug: Slug | null;
  } | null;
  instructor: {
    _id: string;
    _type: "instructor";
    name: string | null;
    bio: string | null;
    photo: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  modules: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "module";
  }> | null;
}>;

// Source: ../../packages/sanity-utils/src/groq/lessons/completeLessonById.ts
// Variable: existingCompletionQuery
// Query: *[_type == "lessonCompletion"    && student._ref == $studentId    && lesson._ref == $lessonId][0]
export type ExistingCompletionQueryResult = {
  _id: string;
  _type: "lessonCompletion";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  student?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "student";
  };
  lesson?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "lesson";
  };
  module?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "module";
  };
  course?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "course";
  };
  completedAt?: string;
} | null;
// Variable: lessonModuleCourseQuery
// Query: *[_type == "lesson" && _id == $lessonId][0]{    _id,    "module": *[_type == "module" && references(^._id)][0]{      _id,      "course": *[_type == "course" && references(^._id)][0]._id    }  }
export type LessonModuleCourseQueryResult = {
  _id: string;
  module: {
    _id: string;
    course: string | null;
  } | null;
} | null;

// Source: ../../packages/sanity-utils/src/groq/lessons/getCourseProgress.ts
// Variable: courseProgressQuery
// Query: {  "completedLessons": *[_type == "lessonCompletion"    && student._ref == $studentId    && course._ref == $courseId]{      _id,      _type,      _createdAt,      _updatedAt,      _rev,      student,      course,      module,      completedAt,      "lesson": lesson->{        _id,        _type,        title,        slug,        description,        videoUrl,        loomUrl,        content,        module      },      "module": module->{        _id,        _type,        title,        lessons,        course      }    },  "course": *[_type == "course" && _id == $courseId][0]{    _id,    _type,    _createdAt,    _updatedAt,    _rev,    title,    price,    slug,    description,    image,    category,    instructor,    "modules": modules[]->{      _id,      _type,      _createdAt,      _updatedAt,      _rev,      title,      course,      "lessons": lessons[]->{        _id,        _type,        title,        slug,        description,        videoUrl,        loomUrl,        content,        module      }    }  }}
export type CourseProgressQueryResult = {
  completedLessons: Array<{
    _id: string;
    _type: "lessonCompletion";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    student: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "student";
    } | null;
    course: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "course";
    } | null;
    module: {
      _id: string;
      _type: "module";
      title: string | null;
      lessons: Array<{
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: "lesson";
      }> | null;
      course: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "course";
      } | null;
    } | null;
    completedAt: string | null;
    lesson: {
      _id: string;
      _type: "lesson";
      title: string | null;
      slug: Slug | null;
      description: string | null;
      videoUrl: string | null;
      loomUrl: string | null;
      content: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
      module: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "module";
      } | null;
    } | null;
  }>;
  course: {
    _id: string;
    _type: "course";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title: string | null;
    price: number | null;
    slug: Slug | null;
    description: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    category: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "category";
    } | null;
    instructor: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "instructor";
    } | null;
    modules: Array<{
      _id: string;
      _type: "module";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title: string | null;
      course: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "course";
      } | null;
      lessons: Array<{
        _id: string;
        _type: "lesson";
        title: string | null;
        slug: Slug | null;
        description: string | null;
        videoUrl: string | null;
        loomUrl: string | null;
        content: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        module: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "module";
        } | null;
      }> | null;
    }> | null;
  } | null;
};

// Source: ../../packages/sanity-utils/src/groq/lessons/getLessonById.ts
// Variable: getLessonByIdQuery
// Query: *[_type == "lesson" && _id == $id][0]{    _id,    _type,    _createdAt,    _updatedAt,    _rev,    title,    slug,    description,    videoUrl,    loomUrl,    content,    module->{      _id,      _type,      _createdAt,      _updatedAt,      _rev,      title,      lessons,      course->{        _id,        _type,        _createdAt,        _updatedAt,        _rev,        title,        price,        slug,        description,        image      }    }  }
export type GetLessonByIdQueryResult = {
  _id: string;
  _type: "lesson";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  videoUrl: string | null;
  loomUrl: string | null;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  module: {
    _id: string;
    _type: "module";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title: string | null;
    lessons: Array<{
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: "lesson";
    }> | null;
    course: {
      _id: string;
      _type: "course";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title: string | null;
      price: number | null;
      slug: Slug | null;
      description: string | null;
      image: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
    } | null;
  } | null;
} | null;

// Source: ../../packages/sanity-utils/src/groq/lessons/getLessonCompletionStatus.ts
// Variable: lessonCompletionStatusQuery
// Query: *[_type == "lessonCompletion"    && student._ref == $studentId    && lesson._ref == $lessonId][0]
export type LessonCompletionStatusQueryResult = {
  _id: string;
  _type: "lessonCompletion";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  student?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "student";
  };
  lesson?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "lesson";
  };
  module?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "module";
  };
  course?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "course";
  };
  completedAt?: string;
} | null;

// Source: ../../packages/sanity-utils/src/groq/lessons/getLessonCompletions.ts
// Variable: getCompletionsQuery
// Query: {  "completedLessons": *[_type == "lessonCompletion"    && student._ref == $studentId    && course._ref == $courseId]{      ...,      "lesson": lesson->{...},      "module": module->{...}    },  "course": *[_type == "course" && _id == $courseId][0]{    ...,    "modules": modules[]->{      ...,      "lessons": lessons[]->{...}    }  }}
export type GetCompletionsQueryResult = {
  completedLessons: Array<{
    _id: string;
    _type: "lessonCompletion";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    student?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "student";
    };
    lesson: {
      _id: string;
      _type: "lesson";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      slug?: Slug;
      description?: string;
      videoUrl?: string;
      loomUrl?: string;
      content?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>;
      module?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "module";
      };
    } | null;
    module: {
      _id: string;
      _type: "module";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      lessons?: Array<{
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: "lesson";
      }>;
      course?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "course";
      };
    } | null;
    course?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "course";
    };
    completedAt?: string;
  }>;
  course: {
    _id: string;
    _type: "course";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    price?: number;
    slug?: Slug;
    description?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    category?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "category";
    };
    modules: Array<{
      _id: string;
      _type: "module";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      lessons: Array<{
        _id: string;
        _type: "lesson";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        title?: string;
        slug?: Slug;
        description?: string;
        videoUrl?: string;
        loomUrl?: string;
        content?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        module?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "module";
        };
      }> | null;
      course?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "course";
      };
    }> | null;
    instructor?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "instructor";
    };
  } | null;
};

// Source: ../../packages/sanity-utils/src/groq/lessons/uncompleteLessonById.ts
// Variable: uncompleteLessonStudentQuery
// Query: *[_type == "student" && clerkId == $clerkId][0]{ _id }
export type UncompleteLessonStudentQueryResult = {
  _id: string;
} | null;
// Variable: uncompleteLessonCompletionQuery
// Query: *[_type == "lessonCompletion"    && student._ref == $studentId    && lesson._ref == $lessonId][0]{ _id }
export type UncompleteLessonCompletionQueryResult = {
  _id: string;
} | null;

// Source: ../../packages/sanity-utils/src/groq/student/getEnrolledCourses.ts
// Variable: getEnrolledCoursesQuery
// Query: *[_type == "student" && clerkId == $clerkId][0]{      "enrolledCourses": *[_type == "enrollment" && student._ref == ^._id]{        _id,        _type,        _createdAt,        _updatedAt,        _rev,        student,        amount,        paymentId,        enrolledAt,        course->{          _id,          _type,          _createdAt,          _updatedAt,          _rev,          title,          price,          slug,          description,          image,          category->{            _id,            _type,            title,            slug          },          instructor->{            _id,            _type,            name,            bio,            photo          },          modules        }      }    }
export type GetEnrolledCoursesQueryResult = {
  enrolledCourses: Array<{
    _id: string;
    _type: "enrollment";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    student: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "student";
    } | null;
    amount: number | null;
    paymentId: string | null;
    enrolledAt: string | null;
    course: {
      _id: string;
      _type: "course";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title: string | null;
      price: number | null;
      slug: Slug | null;
      description: string | null;
      image: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      category: {
        _id: string;
        _type: "category";
        title: string | null;
        slug: Slug | null;
      } | null;
      instructor: {
        _id: string;
        _type: "instructor";
        name: string | null;
        bio: string | null;
        photo: {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
      } | null;
      modules: Array<{
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: "module";
      }> | null;
    } | null;
  }>;
} | null;

// Source: ../../packages/sanity-utils/src/groq/student/getStudentByClerkId.ts
// Variable: getStudentByClerkIdQuery
// Query: *[_type == "student" && clerkId == $clerkId][0]
export type GetStudentByClerkIdQueryResult = {
  _id: string;
  _type: "student";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  clerkId?: string;
  imageUrl?: string;
} | null;

// Source: ../../packages/sanity-utils/src/groq/student/isEnrolledInCourse.ts
// Variable: isEnrolledStudentIdQuery
// Query: *[_type == "student" && clerkId == $clerkId][0]._id
export type IsEnrolledStudentIdQueryResult = string | null;
// Variable: isEnrolledEnrollmentQuery
// Query: *[_type == "enrollment" && student._ref == $studentId && course._ref == $courseId][0]
export type IsEnrolledEnrollmentQueryResult = {
  _id: string;
  _type: "enrollment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  student?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "student";
  };
  course?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "course";
  };
  amount?: number;
  paymentId?: string;
  enrolledAt?: string;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"course\" && _id == $id][0] {\n    _id,\n    _type,\n    _createdAt,\n    _updatedAt,\n    _rev,\n    title,\n    price,\n    slug,\n    description,\n    image,\n    category->{\n      _id,\n      _type,\n      _createdAt,\n      _updatedAt,\n      _rev,\n      title,\n      slug\n    },\n    instructor->{\n      _id,\n      _type,\n      _createdAt,\n      _updatedAt,\n      _rev,\n      name,\n      bio,\n      photo\n    },\n    modules[]->{\n      _id,\n      _type,\n      _createdAt,\n      _updatedAt,\n      _rev,\n      title,\n      course,\n      lessons[]->{\n        _id,\n        _type,\n        _createdAt,\n        _updatedAt,\n        _rev,\n        title,\n        slug,\n        description,\n        videoUrl,\n        loomUrl,\n        content,\n        module\n      }\n    }\n  }\n": GetCourseByIdQueryResult;
    "\n  *[_type == \"course\" && slug.current == $slug][0] {\n    _id,\n    _type,\n    _createdAt,\n    _updatedAt,\n    _rev,\n    title,\n    price,\n    slug,\n    description,\n    image,\n    category->{\n      _id,\n      _type,\n      _createdAt,\n      _updatedAt,\n      _rev,\n      title,\n      slug\n    },\n    instructor->{\n      _id,\n      _type,\n      _createdAt,\n      _updatedAt,\n      _rev,\n      name,\n      bio,\n      photo\n    },\n    modules[]->{\n      _id,\n      _type,\n      _createdAt,\n      _updatedAt,\n      _rev,\n      title,\n      course,\n      lessons[]->{\n        _id,\n        _type,\n        _createdAt,\n        _updatedAt,\n        _rev,\n        title,\n        slug,\n        description,\n        videoUrl,\n        loomUrl,\n        content,\n        module\n      }\n    }\n  }\n": GetCourseBySlugQueryResult;
    "\n  *[_type == \"course\"] {\n    _id,\n    _type,\n    _createdAt,\n    _updatedAt,\n    _rev,\n    title,\n    price,\n    slug,\n    description,\n    image,\n    category->{\n      _id,\n      _type,\n      title,\n      slug\n    },\n    instructor->{\n      _id,\n      _type,\n      name,\n      bio,\n      photo\n    },\n    modules\n  }\n": GetCoursesQueryResult;
    "\n  *[_type == \"course\" && (\n    title match $wildcard ||\n    description match $wildcard ||\n    category->title match $wildcard\n  )] {\n    _id,\n    _type,\n    _createdAt,\n    _updatedAt,\n    _rev,\n    title,\n    price,\n    slug,\n    description,\n    image,\n    category->{\n      _id,\n      _type,\n      title,\n      slug\n    },\n    instructor->{\n      _id,\n      _type,\n      name,\n      bio,\n      photo\n    },\n    modules\n  }\n": SearchCoursesQueryResult;
    "\n  *[_type == \"lessonCompletion\"\n    && student._ref == $studentId\n    && lesson._ref == $lessonId][0]\n": ExistingCompletionQueryResult | LessonCompletionStatusQueryResult;
    "\n  *[_type == \"lesson\" && _id == $lessonId][0]{\n    _id,\n    \"module\": *[_type == \"module\" && references(^._id)][0]{\n      _id,\n      \"course\": *[_type == \"course\" && references(^._id)][0]._id\n    }\n  }\n": LessonModuleCourseQueryResult;
    "\n{\n  \"completedLessons\": *[_type == \"lessonCompletion\"\n    && student._ref == $studentId\n    && course._ref == $courseId]{\n      _id,\n      _type,\n      _createdAt,\n      _updatedAt,\n      _rev,\n      student,\n      course,\n      module,\n      completedAt,\n      \"lesson\": lesson->{\n        _id,\n        _type,\n        title,\n        slug,\n        description,\n        videoUrl,\n        loomUrl,\n        content,\n        module\n      },\n      \"module\": module->{\n        _id,\n        _type,\n        title,\n        lessons,\n        course\n      }\n    },\n  \"course\": *[_type == \"course\" && _id == $courseId][0]{\n    _id,\n    _type,\n    _createdAt,\n    _updatedAt,\n    _rev,\n    title,\n    price,\n    slug,\n    description,\n    image,\n    category,\n    instructor,\n    \"modules\": modules[]->{\n      _id,\n      _type,\n      _createdAt,\n      _updatedAt,\n      _rev,\n      title,\n      course,\n      \"lessons\": lessons[]->{\n        _id,\n        _type,\n        title,\n        slug,\n        description,\n        videoUrl,\n        loomUrl,\n        content,\n        module\n      }\n    }\n  }\n}\n": CourseProgressQueryResult;
    "\n  *[_type == \"lesson\" && _id == $id][0]{\n    _id,\n    _type,\n    _createdAt,\n    _updatedAt,\n    _rev,\n    title,\n    slug,\n    description,\n    videoUrl,\n    loomUrl,\n    content,\n    module->{\n      _id,\n      _type,\n      _createdAt,\n      _updatedAt,\n      _rev,\n      title,\n      lessons,\n      course->{\n        _id,\n        _type,\n        _createdAt,\n        _updatedAt,\n        _rev,\n        title,\n        price,\n        slug,\n        description,\n        image\n      }\n    }\n  }\n": GetLessonByIdQueryResult;
    "\n{\n  \"completedLessons\": *[_type == \"lessonCompletion\"\n    && student._ref == $studentId\n    && course._ref == $courseId]{\n      ...,\n      \"lesson\": lesson->{...},\n      \"module\": module->{...}\n    },\n  \"course\": *[_type == \"course\" && _id == $courseId][0]{\n    ...,\n    \"modules\": modules[]->{\n      ...,\n      \"lessons\": lessons[]->{...}\n    }\n  }\n}\n": GetCompletionsQueryResult;
    "\n  *[_type == \"student\" && clerkId == $clerkId][0]{ _id }\n": UncompleteLessonStudentQueryResult;
    "\n  *[_type == \"lessonCompletion\"\n    && student._ref == $studentId\n    && lesson._ref == $lessonId][0]{ _id }\n": UncompleteLessonCompletionQueryResult;
    "\n    *[_type == \"student\" && clerkId == $clerkId][0]{\n      \"enrolledCourses\": *[_type == \"enrollment\" && student._ref == ^._id]{\n        _id,\n        _type,\n        _createdAt,\n        _updatedAt,\n        _rev,\n        student,\n        amount,\n        paymentId,\n        enrolledAt,\n        course->{\n          _id,\n          _type,\n          _createdAt,\n          _updatedAt,\n          _rev,\n          title,\n          price,\n          slug,\n          description,\n          image,\n          category->{\n            _id,\n            _type,\n            title,\n            slug\n          },\n          instructor->{\n            _id,\n            _type,\n            name,\n            bio,\n            photo\n          },\n          modules\n        }\n      }\n    }\n  ": GetEnrolledCoursesQueryResult;
    "*[_type == \"student\" && clerkId == $clerkId][0]": GetStudentByClerkIdQueryResult;
    "*[_type == \"student\" && clerkId == $clerkId][0]._id": IsEnrolledStudentIdQueryResult;
    "*[_type == \"enrollment\" && student._ref == $studentId && course._ref == $courseId][0]": IsEnrolledEnrollmentQueryResult;
  }
}
